language: ruby
sudo: required
addons:
  postgresql: "9.5.21"
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
rvm:
- 2.7.1
script:
  - bundle install
  - rake db:create
  - rake db:migrate
  - bundle exec rspec
before_install:
  - sudo apt-get update
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
  - sudo cp geckodriver /usr/bin

