services:
  - postgresql
  - docker
addons:
  postgresql: "9.5"
language: ruby
sudo: required
cache: bundler
rvm:
- 2.7.1
script:
  - make test
  - make image
  - bundle install
  - rake db:create RAILS_ENV=test
  - rake db:migrate RAILS_ENV=test
  - bundle exec rspec
before_install:
  - sudo apt-get update
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
  - sudo cp geckodriver /usr/bin
before_script:
  - sudo apt-get update
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-image
  on:
    branch: master
