version: '3.5'
services:
  db:
    image: postgres
    container_name: db.postgres
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bbb-demo
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      .env