default: &default
    adapter: postgresql
    encoding: unicode
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: db
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
development:
    <<: *default
    database: bbb-demo_development
test:
    <<: *default
    database: travis_ci_test
production:
    <<: *default
    encoding: utf8
    database: bbb-demo_production

