# PostgreSQL

development:
  <<: *default
  encoding: unicode
  database: bbb-demo_development
  username: bill
  password: password
  timeout: 5000

test:
  <<: *default
  encoding: unicode
  database: bbb-demo_test
  username: bill
  password: password
  timeout: 5000
  
production:
  <<: *default
  host: ''
  adapter: postgresql
  encoding: utf8
  database: bbb-demo_production
  pool: 5
  username: bill
  password: password 

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
