default: &default
    adapter: postgresql
    encoding: unicode
    host: localhost
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
development:
    <<: *default
    database: bbb-demo_development
    username: bill
    password: password
test:
    <<: *default
    database: travis_ci_test
    username: bill
    password: password
production:
    <<: *default
    host: ""
    encoding: utf8
    database: bbb-demo_production
    pool: 5
    username: bill
    password: password

