default: &default
    adapter: postgresql
    encoding: unicode
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['PG_PASSWORD'] %>
    host: db
    pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
    timeout: 5000
development:
    <<: *default
    database: bbb-demo_development
    url: <%= ENV['DATABASE_URL'].gsub('?', '_development?' ) %>
test:
    <<: *default
    database: travis_ci_test
    url: <%= ENV['DATABASE_URL'].gsub('?', '_test?' ) %>
production:
    <<: *default
    encoding: utf8
    database: bbb-demo_production
    url: <%= ENV['DATABASE_URL'].gsub('?', '_production?' ) %>

